repos:
    - repo: local
      hooks:
        - id: pylint
          name: pylint
          entry: poetry run pylint app/ tests/
          language: system
          always_run: true
          pass_filenames: false
        - id: update requirements 
          name: update requirements
          entry: sh ./scripts/sync_requirements.sh 
          language: system
          always_run: true
          pass_filenames: false

